Repository puppetlabs/vmpooler, pull requests merged in 2023-08, with the labels that each got.

#602 (RE-15692) Do not attempt loading DNS classes if none are defined
  lib/vmpooler/pool_manager.rb
Labels: work in progress, bug

#604 Bump jruby to 9.4.3.0 and bundle update
  .github/workflows/release.yml
  .github/workflows/testing.yml
  Gemfile.lock
  release-prep
  update-gemfile-lock
Labels: enhancement

#606 (maint) Update opentelemetry gems.
  Gemfile.lock
  vmpooler.gemspec
Labels: enhancement

#561 (RE-15162) Update Redis gem to version 5.0.
  Gemfile.lock
  lib/vmpooler.rb
  lib/vmpooler/api/helpers.rb
  lib/vmpooler/api/v3.rb
  lib/vmpooler/pool_manager.rb
  spec/unit/pool_manager_spec.rb
  vmpooler.gemspec
Labels: dependencies, bug

#610 (maint) Release prep for version 3.3.0
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler/version.rb
Labels: maintenance

#612 Update changelog
  CHANGELOG.md
Labels: maintenance

#611 (POD-10) Log reason for failed VM checks.
  lib/vmpooler/api/helpers.rb
  lib/vmpooler/pool_manager.rb
  spec/unit/pool_manager_spec.rb
Labels: enhancement

#614 (maint) Release prep for version 3.4.0
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler/version.rb
Labels: maintenance

#617 (RE-15565) Add ability to use bind_as with a service account
  Gemfile.lock
  docs/configuration.md
  lib/vmpooler/api/helpers.rb
  spec/unit/api/helpers_spec.rb
  vmpooler.yaml.example
Labels: enhancement

#618 (POD-8) Add timeout_notification config to log warning before vm is destroyed.
  Gemfile.lock
  examples/vmpooler.yaml.dummy-example.aliasedpools
  lib/vmpooler.rb
  lib/vmpooler/pool_manager.rb
  spec/unit/pool_manager_spec.rb
  vmpooler.yaml.dummy-example
  vmpooler.yaml.example
Labels: enhancement

#620 (maint) Release prep for version 3.5.0
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler/version.rb
Labels: maintenance

#622 (maint) Release prep for version 3.5.1
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler/version.rb
Labels: maintenance

#624 (maint) Fix message for timeout notification.
  lib/vmpooler/pool_manager.rb
Labels: bug
